server {
    listen        80;
    listen        [::]:80;
    server_name   "";
    root          /home/site/wwwroot/public;
    index         index.php index.html index.htm;

    location / {
        index     index.php index.html index.htm;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Redirigir páginas de error al index principal de Laravel
    error_page 404 /index.php;

    # Pasar los scripts de PHP al servidor FastCGI interno de Azure
    location ~ \.php$ {
        include               fastcgi_params;
        fastcgi_pass          127.0.0.1:9000;
        fastcgi_param         SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
